"""Native colour/rendering checks in an owned disposable profile only."""
import hashlib,json,time,threading,traceback
from http.server import ThreadingHTTPServer,BaseHTTPRequestHandler
from native_support import Browser,ROOT
class Page(BaseHTTPRequestHandler):
 def do_GET(self):
  data=b'<title>SAT fixture</title><style>body{background:white;color:black}@media(prefers-color-scheme:dark){body{background:black;color:white}}</style><body>SAT appearance test</body>'
  self.send_response(200);self.send_header('Content-Type','text/html');self.end_headers();self.wfile.write(data)
 def log_message(self,*args):pass
server=ThreadingHTTPServer(('127.0.0.1',0),Page);threading.Thread(target=server.serve_forever,daemon=True).start()
port=server.server_port
source=(ROOT/'sine/JS/zen-colorscheme-toggle.uc.js').read_text(encoding='utf-8')
result={'sourceSHA256':hashlib.sha256(source.encode()).hexdigest(),'checks':[]}
out=ROOT/'verification'/('native-appearance-'+str(time.time_ns())+'.json')
def check(name,actual,want):
 result['checks'].append({'name':name,'actual':actual,'expected':want,'pass':actual==want})
 print(name,actual==want,actual,flush=True);assert actual==want,(name,actual,want)
def rendering(b):
 return b.content("return {dark:matchMedia('(prefers-color-scheme:dark)').matches,bg:getComputedStyle(document.body).backgroundColor};")
def load(b):
 b.chrome("let sandbox=Cu.Sandbox(window,{sandboxPrototype:window,wantXrays:false});Cu.evalInSandbox(arguments[0],sandbox);",source);time.sleep(.15)
def choose(b,value):b.chrome('window.__zenSiteAppearanceToggle.choose(arguments[0]);',value);time.sleep(.15)
try:
 with Browser() as b:
  profile=b.profile;result['identity']=b.c.identity
  b.navigate(f'http://localhost:{port}/first')
  b.chrome("Services.prefs.setIntPref('layout.css.prefers-color-scheme.content-override',1);Services.prefs.setStringPref('mod.zensiteappearancetoggle.scope','site');window.__first=gBrowser.selectedTab;")
  load(b);check('load preserves native default',b.chrome("return Services.prefs.getIntPref('layout.css.prefers-color-scheme.content-override');"),1)
  b.chrome("document.getElementById('zen-colorscheme-toggle').doCommand();");time.sleep(.15)
  check('toolbar dark choice renders dark',rendering(b),{'dark':True,'bg':'rgb(0, 0, 0)'})
  b.chrome("window.__second=gBrowser.addTab(arguments[0],{triggeringPrincipal:Services.scriptSecurityManager.getSystemPrincipal()});gBrowser.selectedTab=window.__second;",f'http://127.0.0.1:{port}/second');time.sleep(.4)
  check('unrelated site remains light',rendering(b),{'dark':False,'bg':'rgb(255, 255, 255)'})
  check('background first tab stays dark',b.chrome('return window.__first.linkedBrowser.browsingContext.prefersColorSchemeOverride;'),'dark')
  b.navigate(f'http://localhost:{port}/other?q=another');time.sleep(.15)
  check('same website path restores choice',rendering(b),{'dark':True,'bg':'rgb(0, 0, 0)'})
  b.navigate(f'http://127.0.0.1:{port}/back');time.sleep(.15)
  check('destination releases old choice',rendering(b),{'dark':False,'bg':'rgb(255, 255, 255)'})
  choose(b,'system');b.chrome("Services.prefs.setIntPref('ui.systemUsesDarkTheme',1);");time.sleep(.3)
  check('explicit System follows native system dark',rendering(b),{'dark':True,'bg':'rgb(0, 0, 0)'})
  choose(b,'inherit');check('inherit restores global Light',rendering(b),{'dark':False,'bg':'rgb(255, 255, 255)'})
  check('native default still unchanged',b.chrome("return Services.prefs.getIntPref('layout.css.prefers-color-scheme.content-override');"),1)
  check('native public suffix separates tenants',b.chrome("return [Services.eTLD.getBaseDomainFromHost('alice.github.io'),Services.eTLD.getBaseDomainFromHost('bob.github.io'),Services.eTLD.getBaseDomainFromHost('shop.example.co.uk')];"),['alice.github.io','bob.github.io','example.co.uk'])
  b.chrome("Services.prefs.setStringPref('mod.zensiteappearancetoggle.scope','workspace');window.__A=gZenWorkspaces.activeWorkspace;");time.sleep(.15);choose(b,'dark')
  b.chrome('gZenPinnedTabManager.addToEssentials(window.__second);')
  b.chrome("return gZenWorkspaces.createAndSaveWorkspace('Appearance B',undefined,true).then(w=>{window.__B=w.uuid;return true;});")
  b.chrome('return gZenWorkspaces.changeWorkspaceWithID(window.__B);');b.chrome('gBrowser.selectedTab=window.__second;');time.sleep(.2)
  choose(b,'light');check('Essential follows B Light',rendering(b),{'dark':False,'bg':'rgb(255, 255, 255)'})
  b.chrome('return gZenWorkspaces.changeWorkspaceWithID(window.__A);');b.chrome('gBrowser.selectedTab=window.__second;');time.sleep(.2)
  check('Essential follows A Dark',rendering(b),{'dark':True,'bg':'rgb(0, 0, 0)'})
  b.chrome('return gZenWorkspaces.changeWorkspaceWithID(window.__B);');time.sleep(.2)
  check('same Essential changes on actual workspace switch',rendering(b),{'dark':False,'bg':'rgb(255, 255, 255)'})
  b.chrome("Services.prefs.setStringPref('mod.zensiteappearancetoggle.scope','workspace-site');");time.sleep(.15);choose(b,'dark')
  b.chrome('return gZenWorkspaces.changeWorkspaceWithID(window.__A);');time.sleep(.2)
  check('combined mode does not leak to A',rendering(b),{'dark':False,'bg':'rgb(255, 255, 255)'})
  b.chrome('return gZenWorkspaces.changeWorkspaceWithID(window.__B);');time.sleep(.2)
  check('combined mode restores B exception',rendering(b),{'dark':True,'bg':'rgb(0, 0, 0)'})
  b.chrome('window.__zenSiteAppearanceToggle.stop();');time.sleep(.15)
  check('unload clears owned override',rendering(b),{'dark':False,'bg':'rgb(255, 255, 255)'})
  load(b);check('reenable reapplies saved choice',rendering(b),{'dark':True,'bg':'rgb(0, 0, 0)'})
  saved=b.chrome("return Services.prefs.getStringPref('mod.zensiteappearancetoggle.state');")
 with Browser(profile=profile) as b:
  b.navigate(f'http://localhost:{port}/restart')
  b.chrome("Services.prefs.setStringPref('mod.zensiteappearancetoggle.scope','site');")
  load(b);check('saved site persists across browser restart',rendering(b),{'dark':True,'bg':'rgb(0, 0, 0)'})
  check('site records retained across mode changes and restart',b.chrome("return Services.prefs.getStringPref('mod.zensiteappearancetoggle.state');"),saved)
  b.chrome("window.__savedTab=gBrowser.selectedTab;window.__spare=gBrowser.addTab('about:blank',{triggeringPrincipal:Services.scriptSecurityManager.getSystemPrincipal()});gBrowser.selectedTab=window.__spare;")
  check('native discard succeeds',b.chrome('return gBrowser.discardBrowser(window.__savedTab,true);'),True);time.sleep(.3)
  check('controller does not awaken discarded tab',b.chrome("return window.__savedTab.hasAttribute('pending');"),True)
  b.chrome('gBrowser.selectedTab=window.__savedTab;');time.sleep(.4)
  check('restored tab regains saved dark rendering',rendering(b),{'dark':True,'bg':'rgb(0, 0, 0)'})
  b.chrome('window.__otherWin=OpenBrowserWindow();')
  for _ in range(80):
   if b.chrome('return !!window.__otherWin.gBrowserInit?.delayedStartupFinished;'):break
   time.sleep(.1)
  b.chrome('''let win=window.__otherWin;win.gBrowser.selectedTab=win.gBrowser.addTab(arguments[1],{triggeringPrincipal:Services.scriptSecurityManager.getSystemPrincipal()});let sandbox=Cu.Sandbox(win,{sandboxPrototype:win,wantXrays:false});Cu.evalInSandbox(arguments[0],sandbox);''',source,f'http://localhost:{port}/second-window');time.sleep(.5)
  check('second window restores same saved site',b.chrome('return window.__otherWin.gBrowser.selectedBrowser.browsingContext.prefersColorSchemeOverride;'),'dark')
  b.chrome('window.__otherWin.__zenSiteAppearanceToggle.choose("light");');time.sleep(.2)
  check('second-window change synchronises first window rendering',rendering(b),{'dark':False,'bg':'rgb(255, 255, 255)'})
  choose(b,'dark')
  b.chrome('''window.__transferred=window.__otherWin.gBrowser.adoptTab(window.__savedTab,0,true);window.__otherWin.__zenSiteAppearanceToggle.controller.refresh();window.__zenSiteAppearanceToggle.controller.refresh();''');time.sleep(.2)
  check('native tab transfer keeps saved override after source cleanup',b.chrome('return window.__transferred.linkedBrowser.browsingContext.prefersColorSchemeOverride;'),'dark')
  b.chrome('''window.__savedTab=gBrowser.adoptTab(window.__transferred,0,true);window.__zenSiteAppearanceToggle.controller.refresh();window.__otherWin.__zenSiteAppearanceToggle.controller.refresh();''');time.sleep(.2)
  check('tab transferred back retains actual dark rendering',rendering(b),{'dark':True,'bg':'rgb(0, 0, 0)'})
  b.chrome('window.__otherWin.close();');time.sleep(.2)
  choose(b,'inherit');b.chrome("Services.prefs.setIntPref('ui.systemUsesDarkTheme',0);Services.prefs.setIntPref('browser.theme.content-theme',0);Services.prefs.setIntPref('layout.css.prefers-color-scheme.content-override',2);");time.sleep(.3)
  b.navigate(f'http://localhost:{port}/native-system')
  check('native System follows light OS despite dark browser content theme',rendering(b),{'dark':False,'bg':'rgb(255, 255, 255)'})
  check('browser content theme is genuinely dark',b.chrome('return Services.appinfo.contentThemeDerivedColorSchemeIsDark;'),True)
  b.chrome("Services.prefs.setIntPref('layout.css.prefers-color-scheme.content-override',3);");b.navigate(f'http://localhost:{port}/legacy-theme');time.sleep(.2)
  check('legacy browser-theme default renders dark despite light OS',rendering(b),{'dark':True,'bg':'rgb(0, 0, 0)'})
  check('toolbar reads actual legacy browser-theme default',b.chrome('return window.__zenSiteAppearanceToggle.controller.effectiveDark();'),True)
  b.chrome("Services.prefs.setIntPref('browser.theme.content-theme',1);");time.sleep(.3)
  check('toolbar refreshes when inherited content theme becomes light',b.chrome("return document.getElementById('zen-colorscheme-toggle').getAttribute('tooltiptext').includes('to Dark');"),True)
  b.chrome("Services.prefs.setIntPref('browser.theme.content-theme',0);");time.sleep(.3)
  check('toolbar refreshes when inherited content theme becomes dark',b.chrome("return document.getElementById('zen-colorscheme-toggle').getAttribute('tooltiptext').includes('to Light');"),True)
  b.chrome("document.getElementById('zen-colorscheme-toggle').doCommand();");time.sleep(.2)
  check('legacy browser-theme default toggles to rendered light',rendering(b),{'dark':False,'bg':'rgb(255, 255, 255)'})
  b.chrome("Services.prefs.setIntPref('layout.css.prefers-color-scheme.content-override',0);Services.prefs.setIntPref('ui.systemUsesDarkTheme',1);");choose(b,'dark');b.chrome("document.getElementById('zen-colorscheme-toggle').doCommand();");time.sleep(.2)
  check('toggle actually lightens when global and system are both dark',rendering(b),{'dark':False,'bg':'rgb(255, 255, 255)'})
  b.navigate('about:preferences#paneAppearance');time.sleep(.4)
  b.content('''const host=document.createElement('div');host.setAttribute('mod-id','zen-site-appearance-toggle');const inner=document.createElement('div');inner.className='sineItemPreferenceDialogContent';host.appendChild(inner);document.body.appendChild(host);''')
  settings=(ROOT/'sine/JS/appearance-settings.uc.js').read_text(encoding='utf-8')
  b.chrome('''let win=gBrowser.selectedBrowser.contentWindow;let sandbox=Cu.Sandbox(win,{sandboxPrototype:win,wantXrays:false});Cu.evalInSandbox(arguments[0],sandbox);''',settings)
  check('native preferences fixture mounts settings bridge',b.content("return !!document.getElementById('sat-browser-default');"),True)
  check('opening Configure preserves native Dark',b.chrome("return Services.prefs.getIntPref('layout.css.prefers-color-scheme.content-override');"),0)
  b.content("let e=document.getElementById('sat-browser-default');e.value='1';e.dispatchEvent(new Event('change',{bubbles:true}));")
  check('Configure changes actual native default',b.chrome("return Services.prefs.getIntPref('layout.css.prefers-color-scheme.content-override');"),1)
  b.content("document.getElementById('preferences-web-appearance-choice-auto').click();");time.sleep(.2)
  check('real native System chooser writes its actual value',b.chrome("return Services.prefs.getIntPref('layout.css.prefers-color-scheme.content-override');"),2)
  check('real native System chooser is reflected in Configure',b.content("return document.getElementById('sat-browser-default').value;"),'2')
  b.chrome("Services.prefs.setIntPref('layout.css.prefers-color-scheme.content-override',3);")
  check('legacy Auto displays System in Configure',b.content("return document.getElementById('sat-browser-default').value;"),'2')
  check('displaying legacy Auto does not rewrite preference',b.chrome("return Services.prefs.getIntPref('layout.css.prefers-color-scheme.content-override');"),3)
  b.content("let e=document.getElementById('sat-browser-default');e.value='2';e.dispatchEvent(new Event('change',{bubbles:true}));");time.sleep(.2)
  check('Configure System writes native System value',b.chrome("return Services.prefs.getIntPref('layout.css.prefers-color-scheme.content-override');"),2)
  check('Configure System updates actual native chooser',b.content("return document.getElementById('web-appearance-chooser').value;"),'auto')
except Exception as e:result['error']=repr(e);traceback.print_exc()
finally:
 server.shutdown();out.write_text(json.dumps(result,indent=2),encoding='utf-8');print(out,flush=True)
if result.get('error'):raise SystemExit(1)
