// ==UserScript==
// @name zen-colorscheme-toggle
// @description Remember website appearance by workspace or site.
// @author ravenothere
// @version 1.2.0
// ==/UserScript==
// Generated by tools/build.cjs; edit src instead.
(function(){
'use strict';
const SAT_VARIANT="sparkle";
const SAT_SITE_RULES={
  "version": 1,
  "groups": [
    {"key":"service:google-search","label":"Google Search and Images","hosts":["google.com","www.google.com","images.google.com"],"source":"https://support.google.com/websearch/answer/185515"}
  ],
  "separateSubdomains": ["google.com", "microsoft.com", "live.com", "office.com", "amazon.com", "apple.com", "yahoo.com"],
  "note": "These service domains default to independent subdomains except bare/www. Generic sites use the native public suffix service. Keys in version 1 remain stable; corrections can be configured explicitly."
}
;
/* Pure policy shared by all packaged scripts. Never reads browser history. */
const AppearancePolicy = (() => {
  const rules = typeof SAT_SITE_RULES !== 'undefined' ? SAT_SITE_RULES : require('./site-rules.json');
  const values = new Set(['system', 'light', 'dark']);
  const own = (o, k) => Object.prototype.hasOwnProperty.call(o, k);
  const safe = k => typeof k === 'string' && k.length > 0 && !['__proto__','constructor','prototype'].includes(k);
  const record = o => o && typeof o === 'object' && !Array.isArray(o);
  const copy = o => JSON.parse(JSON.stringify(o));
  function emptyStore() { return {version:1, sites:{}, workspaceSites:{}, groups:{}, workspaces:{}}; }
  function hostname(input) {
    if (typeof input !== 'string' || /[\s/*?#@]/.test(input)) throw new Error('Enter an exact hostname, without a URL or wildcard.');
    const u = new URL('https://' + input);
    if (u.port || u.pathname !== '/' || !safe(u.hostname)) throw new Error('Invalid hostname.');
    return u.hostname.replace(/\.$/, '');
  }
  function validKey(k) { return typeof k === 'string' && /^(domain|host|service):[^\s/?#@]+$/.test(k); }
  // Group identities are independent of port; each visited URL supplies its
  // own port. Saved appearance keys retain their existing port separation.
  const groupIdentity=k=>k.replace(/:\d+$/,'');
  function parseStore(raw = '', legacy = '{}') {
    const s = raw ? JSON.parse(raw) : emptyStore();
    if (!record(s) || s.version !== 1) throw new Error('Saved SAT settings use an invalid or unsupported format.');
    for (const name of ['sites','workspaceSites','groups']) {
      s[name] ??= {};
      if (!record(s[name])) throw new Error('Invalid SAT ' + name);
      for (const [k,v] of Object.entries(s[name])) {
        if (!safe(k)) throw new Error('Invalid SAT key');
        if (name === 'groups') {
          if (hostname(k) !== k || !validKey(v)) throw new Error('Invalid site grouping');
        } else if (name === 'sites') {
          if (!validKey(k) || !values.has(v)) throw new Error('Invalid site appearance');
        } else {
          if (!record(v)) throw new Error('Invalid workspace sites');
          for(const [site,value] of Object.entries(v)) if(!validKey(site)||!values.has(value)) throw new Error('Invalid workspace site appearance');
        }
      }
    }
    const old = JSON.parse(legacy);
    if (!record(old)) throw new Error('Invalid legacy workspace map');
    s.workspaces = {};
    for(const [k,v] of Object.entries(old)) {
      if(!safe(k)||![0,1,2].includes(v)) throw new Error('Invalid legacy workspace appearance');
      s.workspaces[k] = ['system','light','dark'][v];
    }
    return s;
  }
  function recogniseSite(url, {baseDomain, userRules = {}}) {
    let u;
    try { u = new URL(url); } catch { return null; }
    if (!['http:','https:'].includes(u.protocol) || u.username || u.password) return null;
    const host = u.hostname.replace(/\.$/,'');
    const suffix = u.port ? ':' + u.port : '';
    if (own(userRules,host)) return {key:groupIdentity(userRules[host])+suffix,label:groupIdentity(userRules[host]).replace(/^[^:]+:/,'')+suffix,host};
    for(const group of rules.groups) if(group.hosts.includes(host)) return {key:group.key+suffix,label:group.label,host};
    let base;
    try { base=baseDomain(host); } catch { base=host; }
    const local = host === 'localhost' || !host.includes('.') || /^[\d.]+$/.test(host) || host.startsWith('[');
    const independent = local || rules.separateSubdomains.includes(base) && ![base,'www.'+base].includes(host);
    const key = (independent?'host:'+host:'domain:'+base)+suffix;
    return {key,label:(independent?host:base)+suffix,host};
  }
  function target(store, {scope,workspaceId,siteKey}, create=false) {
    if(scope==='workspace')return safe(workspaceId)?[store.workspaces,workspaceId]:null;
    if(!validKey(siteKey))return null;
    if(scope==='site')return [store.sites,siteKey];
    if(scope==='workspace-site' && safe(workspaceId)) {
      if(create)store.workspaceSites[workspaceId]??={};
      return [store.workspaceSites[workspaceId]||{},siteKey];
    }
    return null;
  }
  function resolveAppearance(context) {
    const t=target(context.store,context);
    return t && own(t[0],t[1]) ? t[0][t[1]] : 'inherit';
  }
  function setChoice(store,context,value) {
    if(value!=='inherit'&&!values.has(value))throw new Error('Invalid appearance');
    const next=copy(store), t=target(next,context,true);
    if(!t)throw new Error('This page or workspace is not ready for a saved choice.');
    if(value==='inherit')delete t[0][t[1]];else t[0][t[1]]=value;
    return next;
  }
  function setGrouping(store,host,key) {
    host=hostname(host);
    if(key!==null&&!validKey(key))throw new Error('Invalid site group');
    const next=copy(store);
    if(key===null)delete next.groups[host];else next.groups[host]=groupIdentity(key);
    return next;
  }
  function serialize(store) {
    const {workspaces,...state}=store;
    return {state:JSON.stringify(state),legacy:JSON.stringify(Object.fromEntries(Object.entries(workspaces).map(([k,v])=>[k,{system:0,light:1,dark:2}[v]])))};
  }
  return {emptyStore,parseStore,recogniseSite,resolveAppearance,setChoice,setGrouping,serialize};
})();
if (typeof module !== 'undefined') module.exports = AppearancePolicy;

/* Browser-independent lifecycle; native operations live in the environment adapter. */
function createController({environment:env,policy}) {
  const owned=new Map(), yielded=new WeakSet();
  const ownership=env.ownership||new WeakMap(),owner={};
  let running=false,unlisten=()=>{},privateStore=null;
  const read=()=> env.privateWindow ? (privateStore??=env.read()) : env.read();
  function currentContext() {
    const t=env.selected(), raw=t?env.context(t,read()):{};
    return {...raw,siteKey:raw.site?.key||null,scope:env.scope()};
  }
  function restore(bc,state) {
    if(ownership.get(bc)!==state||state.owner!==owner)return;
    try {if(bc.prefersColorSchemeOverride===state.last)bc.prefersColorSchemeOverride=state.before;} catch {}
    ownership.delete(bc);
  }
  function refresh(forceContext=null) {
    if(!running)return;
    try {
      const store=read(), present=new Set();
      for(const tab of env.tabs()) {
        const bc=env.browsingContext(tab);if(!bc)continue;present.add(bc);
        const context=env.context(tab,store);
        const value=policy.resolveAppearance({store,scope:env.scope(),workspaceId:context.workspaceId,siteKey:context.site?.key});
        const want=value==='inherit'?'none':value==='system'?(env.systemDark()?'dark':'light'):value;
        let state=ownership.get(bc);
        if(state&&bc.prefersColorSchemeOverride!==state.last){ownership.delete(bc);owned.delete(bc);yielded.add(bc);state=null;}
        const selectedScope=forceContext &&
          (forceContext.scope==='site'||forceContext.workspaceId===context.workspaceId) &&
          (forceContext.scope==='workspace'||forceContext.siteKey===context.site?.key);
        if(selectedScope)yielded.delete(bc);
        if(yielded.has(bc))continue;
        // Leave unrelated existing overrides alone when SAT has no exception.
        if(!state&&want==='none')continue;
        if(!state)state={before:bc.prefersColorSchemeOverride,last:bc.prefersColorSchemeOverride};
        // A transferred tab keeps its original baseline. The departing window
        // must no longer restore an override now owned by the receiving window.
        state.owner=owner;ownership.set(bc,state);owned.set(bc,state);
        if(want==='none'){restore(bc,state);owned.delete(bc);continue;}
        if(bc.prefersColorSchemeOverride!==want)bc.prefersColorSchemeOverride=want;
        state.last=want;
      }
      for(const [bc,state] of owned)if(!present.has(bc)){restore(bc,state);owned.delete(bc);}
      env.notify();
    }catch(e){env.error(e);}
  }
  function choose(value) {
    const context=currentContext(),next=policy.setChoice(read(),context,value);
    if(env.privateWindow)privateStore=next;else env.write(next);
    refresh(context);
  }
  function effectiveDark() {
    const v=policy.resolveAppearance({...currentContext(),store:read()});
    return v==='inherit'?env.defaultDark():v==='system'?env.systemDark():v==='dark';
  }
  function start(){if(running)return;running=true;unlisten=env.listen(()=>refresh());refresh();}
  function stop(){if(!running)return;running=false;unlisten();for(const [bc,state] of owned)restore(bc,state);owned.clear();}
  return {start,stop,currentContext,choose,refresh,effectiveDark,choice:()=>policy.resolveAppearance({...currentContext(),store:read()})};
}
if(typeof module!=='undefined')module.exports={createController};

const SAT_PREF='layout.css.prefers-color-scheme.content-override';
const SAT_PREFIX='mod.zensiteappearancetoggle.';
const SAT_STATE=SAT_PREFIX+'state', SAT_LEGACY=SAT_PREFIX+'workspacemap';
function satRead(){return AppearancePolicy.parseStore(Services.prefs.getStringPref(SAT_STATE,''),Services.prefs.getStringPref(SAT_LEGACY,'{}'));}
function satWrite(store){
  const raw=AppearancePolicy.serialize(store);
  if(Services.prefs.getStringPref(SAT_STATE,'')!==raw.state)Services.prefs.setStringPref(SAT_STATE,raw.state);
  if(Services.prefs.getStringPref(SAT_LEGACY,'{}')!==raw.legacy)Services.prefs.setStringPref(SAT_LEGACY,raw.legacy);
}
function satScope(win){
  const v=Services.prefs.getStringPref(SAT_PREFIX+'scope','workspace');
  return !win.gZenWorkspaces?'site':['workspace','site','workspace-site'].includes(v)?v:'workspace';
}
function satSite(url,store){return AppearancePolicy.recogniseSite(url,{baseDomain:h=>Services.eTLD.getBaseDomainFromHost(h),userRules:store.groups});}
function satEnvironment(win,notify){
  const system=win.matchMedia('(-moz-system-dark-theme)');
  const {PrivateBrowsingUtils}=ChromeUtils.importESModule('resource://gre/modules/PrivateBrowsingUtils.sys.mjs');
  // CustomizableUI itself is frozen. Share ownership through its browser
  // windows; the weak keys do not keep closed tabs or browsing contexts alive.
  const ownership=Array.from(CustomizableUI.windows).map(w=>w.__satOwnership).find(Boolean)||new WeakMap();
  win.__satOwnership=ownership;
  return {
    ownership,
    tabs:()=>Array.from(win.gBrowser.tabs).filter(t=>!t.closing),
    selected:()=>win.gBrowser.selectedTab,
    browsingContext:t=>t.linkedBrowser?.browsingContext,
    context(t,store){return {workspaceId:(t.hasAttribute('zen-essential')?win.gZenWorkspaces?.activeWorkspace:t.getAttribute('zen-workspace-id'))||null,site:satSite(t.linkedBrowser?.currentURI?.spec||'',store)};},
    read:satRead,write:satWrite,scope:()=>satScope(win),privateWindow:PrivateBrowsingUtils.isWindowPrivate(win),
    systemDark:()=>system.matches,
    defaultDark:()=>{const v=Services.prefs.getIntPref(SAT_PREF,2);return v===0||v!==1&&(v===3?(Services.appinfo?.contentThemeDerivedColorSchemeIsDark??system.matches):system.matches);},
    notify,error:e=>{console.error('[SAT]',e);win.__satError=String(e.message||e);notify();},
    listen(fn){
      let timer=null,alive=true;
      const change=()=>{if(timer===null&&alive)timer=win.setTimeout(()=>{timer=null;fn();},0);};
      const events=['TabSelect','TabOpen','TabClose','TabMove','TabAttrModified','SSTabRestored','TabBrowserInserted'];
      for(const event of events)win.gBrowser.tabContainer.addEventListener(event,change);
      const progress={onLocationChange:change,onStateChange:change,QueryInterface:ChromeUtils.generateQI(['nsIWebProgressListener','nsISupportsWeakReference'])};
      win.gBrowser.addTabsProgressListener(progress);
      const observer=new win.MutationObserver(change);
      observer.observe(win.gBrowser.tabContainer,{subtree:true,attributes:true,attributeFilter:['zen-workspace-id','zen-essential','pending']});
      win.gZenWorkspaces?.addChangeListeners(change);
      win.gZenWorkspaces?.promiseInitialized?.then(change);
      win.addEventListener('ZenWorkspacesUIUpdate',change);
      system.addEventListener('change',change);
      Services.obs?.addObserver(change,'look-and-feel-changed');
      Services.prefs.addObserver(SAT_PREFIX,change);Services.prefs.addObserver(SAT_PREF,change);
      return ()=>{alive=false;if(timer!==null)win.clearTimeout(timer);observer.disconnect();
        for(const event of events)win.gBrowser.tabContainer.removeEventListener(event,change);
        win.gBrowser.removeTabsProgressListener(progress);win.gZenWorkspaces?.removeChangeListeners(change);
        win.removeEventListener('ZenWorkspacesUIUpdate',change);system.removeEventListener('change',change);
        Services.obs?.removeObserver(change,'look-and-feel-changed');
        Services.prefs.removeObserver(SAT_PREFIX,change);Services.prefs.removeObserver(SAT_PREF,change);
      };
    }
  };
}

  const P = {
    ICONSET:          "mod.zensiteappearancetoggle.iconset",
    LIGHTICON:        "mod.zensiteappearancetoggle.lighticon",
    OVERRIDE_MOON:    "mod.zensiteappearancetoggle.override.moon",
    OVERRIDE_SPARKLE: "mod.zensiteappearancetoggle.override.sparkle",
    OVERRIDE_SUN:     "mod.zensiteappearancetoggle.override.sun",
  };

  function makeSrc(svgContent) {
    return "data:image/svg+xml;utf8," + encodeURIComponent(svgContent);
  }

  const ORIG_MOON = makeSrc(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="context-fill" fill-opacity="context-fill-opacity">
    <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>
  </svg>`);

  const ORIG_SPARKLE = makeSrc(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="context-fill" fill-opacity="context-fill-opacity">
    <path d="M16 2c0 0 1.1 5.2 2.8 7 1.7 1.8 6.7 3 6.7 3s-5 1.2-6.7 3c-1.7 1.8-2.8 7-2.8 7s-1.1-5.2-2.8-7C11.5 13.2 6.5 12 6.5 12s5-1.2 6.7-3C14.9 7.2 16 2 16 2z"/>
    <path d="M5.5 2c0 0 .6 2.6 1.6 3.6C8.1 6.6 10.5 7.2 10.5 7.2S8.1 7.8 7.1 8.8C6.1 9.8 5.5 12.4 5.5 12.4S4.9 9.8 3.9 8.8C2.9 7.8.5 7.2.5 7.2S2.9 6.6 3.9 5.6C4.9 4.6 5.5 2 5.5 2z"/>
    <path d="M4.5 14c0 0 .5 2 1.2 2.7C6.4 17.4 8.5 18 8.5 18s-2.1.6-2.8 1.3C5 20 4.5 22 4.5 22s-.5-2-1.2-2.7C2.6 18.6.5 18 .5 18s2.1-.6 2.8-1.3C4 16 4.5 14 4.5 14z"/>
  </svg>`);

  const ORIG_SUN = makeSrc(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="context-fill" fill-opacity="context-fill-opacity">
    <circle cx="12" cy="12" r="4.5"/>
    <rect x="10.75" y="1"  width="2.5" height="4" rx="1.25" ry="1.25"/>
    <rect x="10.75" y="1"  width="2.5" height="4" rx="1.25" ry="1.25" transform="rotate(45 12 12)"/>
    <rect x="10.75" y="1"  width="2.5" height="4" rx="1.25" ry="1.25" transform="rotate(90 12 12)"/>
    <rect x="10.75" y="1"  width="2.5" height="4" rx="1.25" ry="1.25" transform="rotate(135 12 12)"/>
    <rect x="10.75" y="1"  width="2.5" height="4" rx="1.25" ry="1.25" transform="rotate(180 12 12)"/>
    <rect x="10.75" y="1"  width="2.5" height="4" rx="1.25" ry="1.25" transform="rotate(225 12 12)"/>
    <rect x="10.75" y="1"  width="2.5" height="4" rx="1.25" ry="1.25" transform="rotate(270 12 12)"/>
    <rect x="10.75" y="1"  width="2.5" height="4" rx="1.25" ry="1.25" transform="rotate(315 12 12)"/>
  </svg>`);

  const ZEN_MOON    = "chrome://browser/skin/zen-icons/moon-stars.svg";
  const ZEN_SPARKLE = "chrome://browser/skin/zen-icons/sparkles.svg";
  const ZEN_SUN     = "chrome://browser/skin/zen-icons/face-sun.svg";

  function getInt(key, def) {
    try { return Services.prefs.getIntPref(key, def); }
    catch { return def; }
  }

  function resolveIcon(overridePref, origIcon, zenIcon) {
    const override = getInt(overridePref, 0);
    if (override === 1) return origIcon;
    if (override === 2) return zenIcon;
    return getInt(P.ICONSET, 0) === 1 ? zenIcon : origIcon;
  }

  function getMoonSrc() {
    return resolveIcon(P.OVERRIDE_MOON, ORIG_MOON, ZEN_MOON);
  }

  function getLightSrc() {
    return getInt(P.LIGHTICON, 0) === 1
      ? resolveIcon(P.OVERRIDE_SUN, ORIG_SUN, ZEN_SUN)
      : resolveIcon(P.OVERRIDE_SPARKLE, ORIG_SPARKLE, ZEN_SPARKLE);
  }


function startAppearanceToolbar(win){
  const ID='zen-colorscheme-toggle',doc=win.document;
  win.__zenSiteAppearanceToggle?.stop?.();
  let menu=null,controller;
  const scopeNames={workspace:'this workspace',site:'this website','workspace-site':'this website in this workspace'};
  function refresh(){
    const btn=doc.getElementById(ID);if(!btn||!controller)return;
    try{
      const dark=controller.effectiveDark(),ctx=controller.currentContext();
      const text=win.__satError?'Appearance unavailable: '+win.__satError:`Switch ${scopeNames[ctx.scope]} to ${dark?'Light':'Dark'}${ctx.site?' — '+ctx.site.label:''}`;
      btn.setAttribute('tooltiptext',text);btn.setAttribute('aria-label',text);
      const light=SAT_VARIANT==='sun'?ORIG_SUN:SAT_VARIANT==='sparkle'?ORIG_SPARKLE:getLightSrc();
      const src=dark?(SAT_VARIANT==='sine'?getMoonSrc():ORIG_MOON):light;
      const img=btn.querySelector('.toolbarbutton-icon');if(img)img.setAttribute('src',src);
    }catch(e){btn.setAttribute('tooltiptext','SAT: '+e.message);}
  }
  controller=createController({environment:satEnvironment(win,refresh),policy:AppearancePolicy});
  function choose(value){try{controller.choose(value);delete win.__satError;refresh();}catch(e){win.__satError=e.message;refresh();}}
  function toggle(){try{choose(controller.effectiveDark()?'light':'dark');}catch(e){win.__satError=e.message;refresh();}}
  function context(event){
    if(!event.target.closest?.('#'+ID))return;
    event.preventDefault();event.stopPropagation();
    menu?.remove();menu=doc.createXULElement('menupopup');menu.id='sat-appearance-menu';
    const ctx=controller.currentContext();
    for(const [value,label] of [['dark','Dark'],['light','Light'],['system','System'],['inherit','Use browser default']]){
      const item=doc.createXULElement('menuitem');item.id='sat-choice-'+value;
      item.setAttribute('label',label+' — '+scopeNames[ctx.scope]);item.setAttribute('type','radio');item.setAttribute('name','sat-appearance');
      item.setAttribute('checked',String(controller.choice()===value));item.addEventListener('command',()=>choose(value));menu.appendChild(item);
    }
    (doc.getElementById('mainPopupSet')||doc.documentElement).appendChild(menu);menu.openPopupAtScreen(event.screenX,event.screenY,true);
  }
  const api={controller,toggle,refresh,choose,stop(){
    controller.stop();doc.removeEventListener('contextmenu',context,true);win.removeEventListener('unload',api.stop);
    menu?.remove();if(win.__zenSiteAppearanceToggle===api)delete win.__zenSiteAppearanceToggle;
    const any=Array.from(CustomizableUI.windows).some(w=>w.__zenSiteAppearanceToggle);
    if(!any)CustomizableUI.destroyWidget(ID);
  }};
  win.__zenSiteAppearanceToggle=api;
  if(!CustomizableUI.getWidget(ID)?.source)CustomizableUI.createWidget({id:ID,type:'button',defaultArea:CustomizableUI.AREA_NAVBAR,label:'Website Appearance',
    onCreated:btn=>btn.ownerDocument.defaultView.setTimeout(()=>btn.ownerDocument.defaultView.__zenSiteAppearanceToggle?.refresh(),0),
    onCommand:event=>event.target.ownerDocument.defaultView.__zenSiteAppearanceToggle?.toggle()});
  doc.addEventListener('contextmenu',context,true);win.addEventListener('unload',api.stop,{once:true});
  win.addUnloadListener?.(api.stop);
  controller.start();return api;
}
if(document.readyState==='complete')startAppearanceToolbar(window);
else window.addEventListener('load',()=>startAppearanceToolbar(window),{once:true});

})();
