// Generated by tools/build.cjs
(function(){
'use strict';
const SAT_SITE_RULES={
  "version": 1,
  "groups": [
    {"key":"service:google-search","label":"Google Search and Images","hosts":["google.com","www.google.com","images.google.com"],"source":"https://support.google.com/websearch/answer/185515"}
  ],
  "separateSubdomains": ["google.com", "microsoft.com", "live.com", "office.com", "amazon.com", "apple.com", "yahoo.com"],
  "note": "These service domains default to independent subdomains except bare/www. Generic sites use the native public suffix service. Keys in version 1 remain stable; corrections can be configured explicitly."
}
;
/* Pure policy shared by all packaged scripts. Never reads browser history. */
const AppearancePolicy = (() => {
  const rules = typeof SAT_SITE_RULES !== 'undefined' ? SAT_SITE_RULES : require('./site-rules.json');
  const values = new Set(['system', 'light', 'dark']);
  const own = (o, k) => Object.prototype.hasOwnProperty.call(o, k);
  const safe = k => typeof k === 'string' && k.length > 0 && !['__proto__','constructor','prototype'].includes(k);
  const record = o => o && typeof o === 'object' && !Array.isArray(o);
  const copy = o => JSON.parse(JSON.stringify(o));
  function emptyStore() { return {version:1, sites:{}, workspaceSites:{}, groups:{}, workspaces:{}}; }
  function hostname(input) {
    if (typeof input !== 'string' || /[\s/*?#@]/.test(input)) throw new Error('Enter an exact hostname, without a URL or wildcard.');
    const u = new URL('https://' + input);
    if (u.port || u.pathname !== '/' || !safe(u.hostname)) throw new Error('Invalid hostname.');
    return u.hostname.replace(/\.$/, '');
  }
  function validKey(k) { return typeof k === 'string' && /^(domain|host|service):[^\s/?#@]+$/.test(k); }
  // Group identities are independent of port; each visited URL supplies its
  // own port. Saved appearance keys retain their existing port separation.
  const groupIdentity=k=>k.replace(/:\d+$/,'');
  function parseStore(raw = '', legacy = '{}') {
    const s = raw ? JSON.parse(raw) : emptyStore();
    if (!record(s) || s.version !== 1) throw new Error('Saved SAT settings use an invalid or unsupported format.');
    for (const name of ['sites','workspaceSites','groups']) {
      s[name] ??= {};
      if (!record(s[name])) throw new Error('Invalid SAT ' + name);
      for (const [k,v] of Object.entries(s[name])) {
        if (!safe(k)) throw new Error('Invalid SAT key');
        if (name === 'groups') {
          if (hostname(k) !== k || !validKey(v)) throw new Error('Invalid site grouping');
        } else if (name === 'sites') {
          if (!validKey(k) || !values.has(v)) throw new Error('Invalid site appearance');
        } else {
          if (!record(v)) throw new Error('Invalid workspace sites');
          for(const [site,value] of Object.entries(v)) if(!validKey(site)||!values.has(value)) throw new Error('Invalid workspace site appearance');
        }
      }
    }
    const old = JSON.parse(legacy);
    if (!record(old)) throw new Error('Invalid legacy workspace map');
    s.workspaces = {};
    for(const [k,v] of Object.entries(old)) {
      if(!safe(k)||![0,1,2].includes(v)) throw new Error('Invalid legacy workspace appearance');
      s.workspaces[k] = ['system','light','dark'][v];
    }
    return s;
  }
  function recogniseSite(url, {baseDomain, userRules = {}}) {
    let u;
    try { u = new URL(url); } catch { return null; }
    if (!['http:','https:'].includes(u.protocol) || u.username || u.password) return null;
    const host = u.hostname.replace(/\.$/,'');
    const suffix = u.port ? ':' + u.port : '';
    if (own(userRules,host)) return {key:groupIdentity(userRules[host])+suffix,label:groupIdentity(userRules[host]).replace(/^[^:]+:/,'')+suffix,host};
    for(const group of rules.groups) if(group.hosts.includes(host)) return {key:group.key+suffix,label:group.label,host};
    let base;
    try { base=baseDomain(host); } catch { base=host; }
    const local = host === 'localhost' || !host.includes('.') || /^[\d.]+$/.test(host) || host.startsWith('[');
    const independent = local || rules.separateSubdomains.includes(base) && ![base,'www.'+base].includes(host);
    const key = (independent?'host:'+host:'domain:'+base)+suffix;
    return {key,label:(independent?host:base)+suffix,host};
  }
  function target(store, {scope,workspaceId,siteKey}, create=false) {
    if(scope==='workspace')return safe(workspaceId)?[store.workspaces,workspaceId]:null;
    if(!validKey(siteKey))return null;
    if(scope==='site')return [store.sites,siteKey];
    if(scope==='workspace-site' && safe(workspaceId)) {
      if(create)store.workspaceSites[workspaceId]??={};
      return [store.workspaceSites[workspaceId]||{},siteKey];
    }
    return null;
  }
  function resolveAppearance(context) {
    const t=target(context.store,context);
    return t && own(t[0],t[1]) ? t[0][t[1]] : 'inherit';
  }
  function setChoice(store,context,value) {
    if(value!=='inherit'&&!values.has(value))throw new Error('Invalid appearance');
    const next=copy(store), t=target(next,context,true);
    if(!t)throw new Error('This page or workspace is not ready for a saved choice.');
    if(value==='inherit')delete t[0][t[1]];else t[0][t[1]]=value;
    return next;
  }
  function setGrouping(store,host,key) {
    host=hostname(host);
    if(key!==null&&!validKey(key))throw new Error('Invalid site group');
    const next=copy(store);
    if(key===null)delete next.groups[host];else next.groups[host]=groupIdentity(key);
    return next;
  }
  function serialize(store) {
    const {workspaces,...state}=store;
    return {state:JSON.stringify(state),legacy:JSON.stringify(Object.fromEntries(Object.entries(workspaces).map(([k,v])=>[k,{system:0,light:1,dark:2}[v]])))};
  }
  return {emptyStore,parseStore,recogniseSite,resolveAppearance,setChoice,setGrouping,serialize};
})();
if (typeof module !== 'undefined') module.exports = AppearancePolicy;

const SAT_PREF='layout.css.prefers-color-scheme.content-override';
const SAT_PREFIX='mod.zensiteappearancetoggle.';
const SAT_STATE=SAT_PREFIX+'state', SAT_LEGACY=SAT_PREFIX+'workspacemap';
function satRead(){return AppearancePolicy.parseStore(Services.prefs.getStringPref(SAT_STATE,''),Services.prefs.getStringPref(SAT_LEGACY,'{}'));}
function satWrite(store){
  const raw=AppearancePolicy.serialize(store);
  if(Services.prefs.getStringPref(SAT_STATE,'')!==raw.state)Services.prefs.setStringPref(SAT_STATE,raw.state);
  if(Services.prefs.getStringPref(SAT_LEGACY,'{}')!==raw.legacy)Services.prefs.setStringPref(SAT_LEGACY,raw.legacy);
}
function satScope(win){
  const v=Services.prefs.getStringPref(SAT_PREFIX+'scope','workspace');
  return !win.gZenWorkspaces?'site':['workspace','site','workspace-site'].includes(v)?v:'workspace';
}
function satSite(url,store){return AppearancePolicy.recogniseSite(url,{baseDomain:h=>Services.eTLD.getBaseDomainFromHost(h),userRules:store.groups});}
function satEnvironment(win,notify){
  const system=win.matchMedia('(-moz-system-dark-theme)');
  const {PrivateBrowsingUtils}=ChromeUtils.importESModule('resource://gre/modules/PrivateBrowsingUtils.sys.mjs');
  // CustomizableUI itself is frozen. Share ownership through its browser
  // windows; the weak keys do not keep closed tabs or browsing contexts alive.
  const ownership=Array.from(CustomizableUI.windows).map(w=>w.__satOwnership).find(Boolean)||new WeakMap();
  win.__satOwnership=ownership;
  return {
    ownership,
    tabs:()=>Array.from(win.gBrowser.tabs).filter(t=>!t.closing),
    selected:()=>win.gBrowser.selectedTab,
    browsingContext:t=>t.linkedBrowser?.browsingContext,
    context(t,store){return {workspaceId:(t.hasAttribute('zen-essential')?win.gZenWorkspaces?.activeWorkspace:t.getAttribute('zen-workspace-id'))||null,site:satSite(t.linkedBrowser?.currentURI?.spec||'',store)};},
    read:satRead,write:satWrite,scope:()=>satScope(win),privateWindow:PrivateBrowsingUtils.isWindowPrivate(win),
    systemDark:()=>system.matches,
    defaultDark:()=>{const v=Services.prefs.getIntPref(SAT_PREF,2);return v===0||v!==1&&(v===3?(Services.appinfo?.contentThemeDerivedColorSchemeIsDark??system.matches):system.matches);},
    notify,error:e=>{console.error('[SAT]',e);win.__satError=String(e.message||e);notify();},
    listen(fn){
      let timer=null,alive=true;
      const change=()=>{if(timer===null&&alive)timer=win.setTimeout(()=>{timer=null;fn();},0);};
      const events=['TabSelect','TabOpen','TabClose','TabMove','TabAttrModified','SSTabRestored','TabBrowserInserted'];
      for(const event of events)win.gBrowser.tabContainer.addEventListener(event,change);
      const progress={onLocationChange:change,onStateChange:change,QueryInterface:ChromeUtils.generateQI(['nsIWebProgressListener','nsISupportsWeakReference'])};
      win.gBrowser.addTabsProgressListener(progress);
      const observer=new win.MutationObserver(change);
      observer.observe(win.gBrowser.tabContainer,{subtree:true,attributes:true,attributeFilter:['zen-workspace-id','zen-essential','pending']});
      win.gZenWorkspaces?.addChangeListeners(change);
      win.gZenWorkspaces?.promiseInitialized?.then(change);
      win.addEventListener('ZenWorkspacesUIUpdate',change);
      system.addEventListener('change',change);
      Services.obs?.addObserver(change,'look-and-feel-changed');
      Services.prefs.addObserver(SAT_PREFIX,change);Services.prefs.addObserver(SAT_PREF,change);
      return ()=>{alive=false;if(timer!==null)win.clearTimeout(timer);observer.disconnect();
        for(const event of events)win.gBrowser.tabContainer.removeEventListener(event,change);
        win.gBrowser.removeTabsProgressListener(progress);win.gZenWorkspaces?.removeChangeListeners(change);
        win.removeEventListener('ZenWorkspacesUIUpdate',change);system.removeEventListener('change',change);
        Services.obs?.removeObserver(change,'look-and-feel-changed');
        Services.prefs.removeObserver(SAT_PREFIX,change);Services.prefs.removeObserver(SAT_PREF,change);
      };
    }
  };
}

/* Runs in about:preferences, without browser-window globals. */
(function settings(){
  window.__satSettings?.stop();
  const doc=window.document,html='http://www.w3.org/1999/xhtml';let panel=null,refreshPanel=()=>{},stopped=false;
  const el=(tag,text)=>{const e=doc.createElementNS(html,tag);if(text)e.textContent=text;return e;};
  function mount(){
    if(stopped||panel?.isConnected)return;
    const host=doc.querySelector('[mod-id="zen-site-appearance-toggle"] .sineItemPreferenceDialogContent');if(!host)return;
    panel=el('section');panel.id='sat-settings-panel';panel.style.cssText='display:grid;gap:10px;padding:12px 0';
    panel.appendChild(el('h3','Remember website appearance'));
    function select(id,label,options){
      const row=el('label',label+' '),input=el('select');input.id=id;
      for(const [value,text]of options){const o=el('option',text);o.value=value;input.appendChild(o);}
      row.appendChild(input);panel.appendChild(row);return input;
    }
    const defaults=select('sat-browser-default','Browser default',[[2,'System'],[1,'Light'],[0,'Dark']]);
    const hasWorkspaces=Services.appinfo?.name?.toLowerCase().includes('zen');
    const scope=select('sat-scope','Remember choices',hasWorkspaces?[['workspace','Per workspace'],['site','Per site'],['workspace-site','Per site within each workspace']]:[['site','Per site']]);
    panel.appendChild(el('p','The toolbar saves your choice for this scope. Use browser default removes an exception. Websites with their own explicit theme settings may need to be set to follow the device.'));
    panel.appendChild(el('h3','Site grouping'));
    const row=el('label','Exact hostname '),hostname=el('input');hostname.id='sat-group-host';hostname.type='text';hostname.placeholder='shop.example.com';row.appendChild(hostname);panel.appendChild(row);
    const groups=select('sat-group-target','Group',[['automatic','Automatic'],['independent','Keep this hostname separate']]);
    const preview=el('p');preview.id='sat-group-preview';panel.appendChild(preview);
    const button=el('button','Apply grouping');button.type='button';button.id='sat-group-apply';panel.appendChild(button);
    const existing=el('ul');existing.id='sat-saved-groups';panel.appendChild(existing);
    const message=el('p');message.id='sat-settings-message';message.setAttribute('role','status');panel.appendChild(message);
    function previewChoice(){
      try{
        if(!hostname.value.trim()){preview.textContent='Enter a hostname to preview its group and remembered appearance.';return;}
        const s=satRead(),target=groups.value==='automatic'?null:groups.value==='independent'?'host:'+new URL('https://'+hostname.value.trim()).hostname:groups.value;
        const next=AppearancePolicy.setGrouping(s,hostname.value.trim(),target);
        const site=AppearancePolicy.recogniseSite('https://'+hostname.value.trim(),{baseDomain:h=>Services.eTLD.getBaseDomainFromHost(h),userRules:next.groups});
        const label=v=>({dark:'Dark',light:'Light',system:'System',inherit:'the browser default'})[v||'inherit'];
        let detail;
        if(scope.value==='workspace')detail='Per workspace is selected, so grouping does not change the workspace appearance.';
        else if(scope.value==='site')detail='This site will use '+label(s.sites[site.key])+'.';
        else {
          const saved=Object.entries(s.workspaceSites).filter(([,choices])=>choices[site.key]);
          let workspaces;
          try{workspaces=Services.wm?.getMostRecentWindow('navigator:browser')?.gZenWorkspaces;}catch{}
          detail=saved.length?saved.map(([id,choices],i)=>`${workspaces?.getWorkspaceFromId(id)?.name||'Saved workspace '+(i+1)}: ${label(choices[site.key])}`).join('; ')+'. Other workspaces use the browser default.':'No workspace has a saved choice for this group; the browser default applies.';
        }
        preview.textContent=`Group: ${site.label}. ${detail} Grouping applies across workspaces; earlier choices are retained. Non-default ports keep separate choices.`;
      }catch(e){message.textContent=e.message;}
    }
    refreshPanel=()=>{
      // Zen's native chooser uses 2 for System; legacy Firefox Auto is 3.
      // Display either as System without changing the stored preference.
      const nativeDefault=Services.prefs.getIntPref(SAT_PREF,2);
      defaults.value=String(nativeDefault===0||nativeDefault===1?nativeDefault:2);
      scope.value=hasWorkspaces?Services.prefs.getStringPref(SAT_PREFIX+'scope','workspace'):'site';
      try{
        const s=satRead(),selected=groups.value;
        const keys=new Set([...Object.keys(s.sites),...Object.values(s.groups),...Object.values(s.workspaceSites).flatMap(Object.keys)]);
        while(groups.options.length>2)groups.remove(2);
        for(const key of [...keys].sort()){const o=el('option',key.replace(/^[^:]+:/,''));o.value=key;groups.appendChild(o);}
        groups.value=[...groups.options].some(o=>o.value===selected)?selected:'automatic';
        existing.replaceChildren();
        for(const [host,key]of Object.entries(s.groups)){const li=el('li');const edit=el('button',host+' → '+key.replace(/^[^:]+:/,''));edit.type='button';edit.addEventListener('click',()=>{hostname.value=host;groups.value=key;previewChoice();hostname.focus();});li.appendChild(edit);existing.appendChild(li);}
        previewChoice();
      }catch(e){message.textContent=e.message;}
    };
    defaults.addEventListener('change',()=>Services.prefs.setIntPref(SAT_PREF,Number(defaults.value)));
    scope.addEventListener('change',()=>Services.prefs.setStringPref(SAT_PREFIX+'scope',scope.value));
    groups.addEventListener('change',previewChoice);hostname.addEventListener('input',previewChoice);
    button.addEventListener('click',()=>{
      try{
        const current=satRead();let target=groups.value==='automatic'?null:groups.value;
        if(target==='independent')target='host:'+new URL('https://'+hostname.value.trim()).hostname;
        satWrite(AppearancePolicy.setGrouping(current,hostname.value.trim(),target));message.textContent='Grouping saved. Existing appearance choices have been retained.';refreshPanel();
      }catch(e){message.textContent=e.message;}
    });
    host.prepend(panel);refreshPanel();
    const {PrivateBrowsingUtils}=ChromeUtils.importESModule('resource://gre/modules/PrivateBrowsingUtils.sys.mjs');
    if(PrivateBrowsingUtils.isContentWindowPrivate(window)){
      for(const control of panel.querySelectorAll('input,select,button'))control.disabled=true;
      message.textContent='Change saved configuration from a normal window. Toolbar choices in private windows are temporary.';
    }
  }
  const observer=new MutationObserver(mount);observer.observe(doc.documentElement,{childList:true,subtree:true});
  const update=()=>refreshPanel();Services.prefs.addObserver(SAT_PREFIX,update);Services.prefs.addObserver(SAT_PREF,update);
  const api={stop(){if(stopped)return;stopped=true;observer.disconnect();Services.prefs.removeObserver(SAT_PREFIX,update);Services.prefs.removeObserver(SAT_PREF,update);window.removeEventListener('unload',api.stop);panel?.remove();if(window.__satSettings===api)delete window.__satSettings;}};
  window.__satSettings=api;window.addEventListener('unload',api.stop,{once:true});window.addUnloadListener?.(api.stop);mount();
})();

})();
