const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const modules=['appearance-policy','appearance-controller','appearance-browser','appearance-icons','appearance-toolbar'];
const outputs={'sine/JS/zen-colorscheme-toggle.uc.js':'sine','chrome/JS/moon-sparkle/zen-colorscheme-toggle-sparkle.uc.js':'sparkle','chrome/JS/moon-sun/zen-colorscheme-toggle-sun.uc.js':'sun'};
for(const [file,variant]of Object.entries(outputs)){
  const source=`// ==UserScript==\n// @name zen-colorscheme-toggle\n// @description Remember website appearance by workspace or site.\n// @author ravenothere\n// @version 1.2.0\n// ==/UserScript==\n// Generated by tools/build.cjs; edit src instead.\n(function(){\n'use strict';\nconst SAT_VARIANT=${JSON.stringify(variant)};\nconst SAT_SITE_RULES=${read('src/site-rules.json')};\n${modules.map(n=>read('src/'+n+'.js')).join('\n')}\n})();\n`;
  if(process.argv.includes('--check')){if(read(file)!==source)throw Error('Stale generated script: '+file);}else fs.writeFileSync(path.join(root,file),source);
}
console.log('Three standalone scripts '+(process.argv.includes('--check')?'match source.':'built.'));
const settings=`// Generated by tools/build.cjs\n(function(){\n'use strict';\nconst SAT_SITE_RULES=${read('src/site-rules.json')};\n${['appearance-policy','appearance-browser','appearance-settings'].map(n=>read('src/'+n+'.js')).join('\n')}\n})();\n`;
const settingsPath='sine/JS/appearance-settings.uc.js';
if(process.argv.includes('--check')){if(read(settingsPath)!==settings)throw Error('Stale settings script');}else fs.writeFileSync(path.join(root,settingsPath),settings);
